static COUNTER: AtomicU64 = AtomicU64::new(0);

fn get_rng() -> impl Rng {
    ChaCha20Rng::try_from_rng(&mut SysRng).unwrap()
}

#[proc_macro]
/// Generates a compile-time CSPRNG random u64 number.
pub fn random_u64(_input: TokenStream) -> TokenStream {
    get_rng()
        .next_u64()
        .to_string()
        .parse()
        .expect("u64 literal should parse")
}

#[proc_macro]
/// Generates a compile-time CSPRNG random u32 number.
pub fn random_u32(_input: TokenStream) -> TokenStream {
    get_rng()
        .next_u32()
        .to_string()
        .parse()
        .expect("u32 literal should parse")
}

#[proc_macro]
/// Generates a compile-time CSPRNG random byte array of the specified size: `[u8; size]`.
///
/// ### Example
/// ```rust
/// let key = random_bytes!(32); // Generates a [u8; 32] array at compile time
/// ```
pub fn random_bytes(input: TokenStream) -> TokenStream {
    let tokens: Vec<TokenTree> = input.into_iter().collect();

    let size: usize = match tokens.as_slice() {
        [TokenTree::Literal(lit)] => {
            let lit_str = lit.to_string();
            // Strip any type suffixes (e.g. "12_usize", "12i32") and whitespace
            let clean_str: String = lit_str.chars().take_while(|c| c.is_ascii_digit()).collect();

            clean_str.parse().expect("Failed to parse integer literal")
        }
        _ => panic!("random_bytes! expects a single integer literal, e.g., random_bytes!(12)"),
    };

    let mut rng = get_rng();
    let mut bytes = vec![0u8; size];
    rng.fill_bytes(&mut bytes);

    // Format the bytes into a Rust array literal token stream (e.g., "[12u8, 244u8, ...]")
    let mut array_literal = String::new();
    array_literal.push('[');

    for (i, byte) in bytes.iter().enumerate() {
        if i > 0 {
            array_literal.push_str(", ");
        }

        array_literal.push_str(&format!("{}u8", byte));
    }

    array_literal.push(']');
    array_literal
        .parse()
        .expect("Generated byte array literal should parse as TokenStream")
}

#[proc_macro]
/// Generates a compile-time simple random u64 number.
pub fn simple_random_u64(_input: TokenStream) -> TokenStream {
    make_simple_random_u64()
        .to_string()
        .parse()
        .expect("u64 literal should parse")
}

#[proc_macro]
/// Generates a compile-time simple random u32 number.
pub fn simple_random_u32(_input: TokenStream) -> TokenStream {
    make_simple_random_u32()
        .to_string()
        .parse()
        .expect("u32 literal should parse")
}

fn make_simple_random_u64() -> u64 {
    let mut seed = _simple_random_u64();

    for _ in 0..3 {
        seed ^= _simple_random_u64();
    }

    seed
}

fn make_simple_random_u32() -> u32 {
    _simple_random_u64() as u32
}

fn _simple_random_u64() -> u64 {
    let counter = COUNTER.fetch_add(1, Ordering::Relaxed);
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default();

    let mut hasher = DefaultHasher::new();

    counter.hash(&mut hasher);
    now.hash(&mut hasher);
    std::process::id().hash(&mut hasher);

    hasher.finish()
}
